spring:
    profiles:
        active: 
        - prod

    # datasource:
    #     url: jdbc:mysql://localhost:3306/school
    #     username: user
    #     password: password
    

---
spring:
    profiles: prod
    
    datasource:
        url: jdbc:h2:file:./school
    jpa:
        hibernate:
            ddl-auto: update